services:
  database:
    image: mariadb:11
    container_name: phufa-database
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - backend-net

  proxy:
    image: openresty/openresty:alpine
    container_name: phufa-proxy
    restart: always
    ports:
      - 80:80
    volumes:
      - ./proxy/logs:/var/log/nginx
      - ./proxy/html:/usr/share/nginx/html
      - ./proxy/conf:/etc/nginx/conf.d/
      - type: bind
        source: ./proxy/nginx.conf
        target: /usr/local/openresty/nginx/conf/nginx.conf
    networks:
      - app-network
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: phufa-frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules/
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: phufa-backend
    restart: always
    volumes:
      - ./backend:/app
      - ./.env:/app/.env
      - /app/node_modules/
    networks:
      - app-network
      - backend-net
    working_dir: /app
    depends_on:
      - database

  init-db:
    build:
      context: ./init-db
      dockerfile: Dockerfile
    container_name: phufa-init-db
    restart: "no"
    depends_on:
      - database
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - backend-net

networks:
  app-network:
  backend-net: